name: space_shared
version: 0.1.0
author: Heikki Haapala <hhaapala@gmail.com>
dependencies:
  siege_engine:
    git: git://github.com/Absor/siege_engine.git

#dependencies:
#  js: any
#  unittest: any